config/routes.rb
Rails.application.routes.draw do
  resources :animals
  get "/api/taxonomy" => "animals#taxonomy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animals_controller.rb
require 'httparty'

class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
    # puts params
    @suspensions = legislation(params[:id])
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def taxonomy
    url = 'https://api.speciesplus.net/api/v1/taxon_concepts'
    headers = {
      "X-Authentication-Token": 'Rk7DfB3l25nsX6zV4qozTQtt'
    }

    response = HTTParty.get(url, headers: headers)

    for taxonomy in response["taxon_concepts"]
      @animal = Animal.new(animal_fixture(taxonomy))
      @animal.save!
    end
    
    redirect_to :index
  end

  def legislation(cites_id)
    taxonimic_id = cites_id
    url = "https://api.speciesplus.net/api/v1/taxon_concepts/#{taxonimic_id}/cites_legislation"
    headers = {
      "X-Authentication-Token": 'Rk7DfB3l25nsX6zV4qozTQtt'
    }

    response = HTTParty.get(url, headers: headers)

    suspensions = []

    for suspension in response["cites_suspensions"]
      suspensions << {
        notes: suspension["notes"],
        country: suspension["geo_entity"]["name"],
        cite: suspension["start_notification"]["name"],
        date: suspension["start_notification"]["date"],
        url: suspension["start_notification"]["url"]
      }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:cites_id, :common_name, :kingdom, :phylum, :animal_class, :order, :family)
    end

    def animal_fixture(data)
      common_name = ""
      # byebug
      for name in data["common_names"]
        common_name << name['name']
        common_name << ","
      end
      
      kingdom = data["higher_taxa"]["kingdom"] || ""
      phylum = data["higher_taxa"]["phylum"] || ""
      animal_class = data["higher_taxa"]["class"] || ""
      order = data["higher_taxa"]["order"] || ""
      family = data["higher_taxa"]["family"] || ""

      params = {cites_id: data["id"], common_name: common_name, kingdom: kingdom, phylum: phylum, animal_class: animal_class,  order: order, family: family}
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cites_id %>
    <%= form.number_field :cites_id %>
  </div>

  <div class="field">
    <%= form.label :common_name %>
    <%= form.text_area :common_name %>
  </div>

  <div class="field">
    <%= form.label :kingdom %>
    <%= form.text_area :kingdom %>
  </div>

  <div class="field">
    <%= form.label :phylum %>
    <%= form.text_area :phylum %>
  </div>

  <div class="field">
    <%= form.label :class %>
    <%= form.text_area :class %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.text_area :order %>
  </div>

  <div class="field">
    <%= form.label :family %>
    <%= form.text_area :family %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Animals</h1>

<table>
  <thead>
    <tr>
      <th>Cites</th>
      <th>Common name</th>
      <th>Kingdom</th>
      <th>Phylum</th>
      <th>Class</th>
      <th>Order</th>
      <th>Family</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.cites_id %></td>
        <td><%= animal.common_name %></td>
        <td><%= animal.kingdom %></td>
        <td><%= animal.phylum %></td>
        <td><%= animal.animal_class %></td>
        <td><%= animal.order %></td>
        <td><%= animal.family %></td>
        <td><%= link_to 'Show', animal %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animal', new_animal_path %>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cites:</strong>
  <%= @animal.cites_id %>
</p>

<p>
  <strong>Common name:</strong>
  <%= @animal.common_name %>
</p>

<p>
  <strong>Kingdom:</strong>
  <%= @animal.kingdom %>
</p>

<p>
  <strong>Phylum:</strong>
  <%= @animal.phylum %>
</p>

<p>
  <strong>Class:</strong>
  <%= @animal.animal_class %>
</p>

<p>
  <strong>Order:</strong>
  <%= @animal.order %>
</p>

<p>
  <strong>Family:</strong>
  <%= @animal.family %>
</p>
<p>
  <strong>Legislations:</strong>
  <% @suspensions.each do |suspension| %>
    <p><%= suspension["notes"] %>
    <p><%= suspension["geo_entity"]["name"] %>
    <p><%= suspension["start_notification"]["name"] %>
    <p><%= suspension["start_notification"]["date"] %>
    <p><%= suspension["start_notification"]["url"] %>
  <% end%>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

app/views/animals/taxomy.html..erb
<h1>Taxonomy Bitch</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AndelaZoo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>